GET http://localhost:3500/api/users

###
# Test Signup API
POST http://localhost:3500/api/auth/signup
Content-Type: application/json

{
  "name": "ade5",
  "email": "ade5@example.com",
  "password": "ade_pass5",
  "role": "Mahasiswa",
  "subRole": "Asisten Lab"
}

###
# Test Login API
POST http://localhost:3500/api/auth/login
Content-Type: application/json

{
  "email": "ade5@example.com",
  "password": "ade_pass5"
}


###
# Endpoint untuk mengambil data pengguna
GET http://localhost:3500/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6Ik1haGFzaXN3YSIsImlhdCI6MTczNDAyNDE1OCwiZXhwIjoxNzM0MDI3NzU4fQ.PJwqpNWILAWJmOi_WSs60fHUC6GoWrhwZZPumAwUfMc"
Content-Type: application/json
