GET http://localhost:3500/api/users

###
# Test Signup API
POST http://localhost:3500/api/auth/signup
Content-Type: application/json

{
  "name": "ade5",
  "email": "ade5@example.com",
  "password": "ade_pass5",
  "role": "Mahasiswa",
  "subRole": "Asisten Lab"
}

###
# Test Login API
POST http://localhost:3500/api/auth/login
Content-Type: application/json

{
  "username": "ade5@example.com",
  "password": "ade_pass5"
}

###
GET http://localhost:3500/api/profile
Accept: application/json

###
GET http://localhost:3500/api/monitoring
Accept: application/json

###
# Mendapatkan data alat berdasarkan lab_name
GET http://localhost:3500/api/monitoring
Content-Type: application/json


###
## Menambahkan atau update item 
POST http://localhost:3500/api/monitoring/add_item
Content-Type: application/json

{
  "lab_name": "RPL",
  "item_name": "Printer 3D",
  "total": 2,
  "available": 2,
  "broken": 0,
  "under_repair": 0
}

###
GET http://localhost:3500/api/profile