# Test Signup API
POST http://localhost:3001/api/signup
Content-Type: application/json

{
  "username": "dea_afriza",
  "email": "dea@example.com",
  "password": "password12345",
  "role": "Mahasiswa Umum",
  "subRole": "Asisten Lab"
}

###

# Test Login API
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "dea@example.com",
  "password": "password12345"
}
